'Task: Code':
- changed-files:
  - any-glob-to-any-file: 'Scripts/**'
    
'Task: Modelling':
- changed-files:
  - any-glob-to-any-file: 'Models/**'

'Scene: Dungeon':
- changed-files:
  - any-glob-to-any-file: ['Scripts/Dungeon/**', 'Scene/Dungeon.cs']
    
'Scene: Main Menu':
- changed-files:
  - any-glob-to-any-file: 'Scene/MainMenu.cs'

'Task: Godot':
- changed-files:
  - any-glob-to-any-file: ['project.godot', 'addons/**', '*.csproj', '*.sln']
