name: Godot Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always
  CSharpVersion: 8.0.x

jobs:
  build-godot:
    strategy:
      fail-fast: false
      matrix:
        godot-version: [4.2.1]

    runs-on: self-hosted
    container: ubuntu:lunar-20231128

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: APT update
        run: apt update

      - name: APT install cURL
        run: apt install -y curl

      - name: APT install unzip
        run: apt install -y unzip

      - name: APT install libicu-dev
        run: apt install -y libicu-dev

      - uses: actions/setup-dotnet@v4
        name: Setup .NET SDK
        with:
          dotnet-version: ${{ env.CSharpVersion }}

      - name: Remove godot syslink if it exists
        run: |
          rm -rf /github/home/bin/godot || true
          rm -rf /github/home/bin/GodotSharp || true
          rm -rf /github/home/godot || true

      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          # Version must include major, minor, and patch, and be >= 4.0.0
          version: ${{ matrix.godot-version }}
          # Use .NET-enabled version of Godot (the default is also true).
          use-dotnet: true

      - name: Build Project
        run: |
          cd "Godot Project"
          dotnet restore
          godot --headless --build-solutions --quit || exit 0
          dotnet build

  # build-rust:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       rust-channel: ["stable"]

  #   runs-on: self-hosted
  #   container: ubuntu:lunar-20231128

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: APT update
  #       run: apt update

  #     - name: APT install cURL
  #       run: apt install -y curl

  #     - name: APT install build-essential
  #       run: apt install -y build-essential

  #     - name: Install Rust
  #       run: curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable

  #     - name: Release Build
  #       run: |
  #         cd "Match Maker Server"
  #         source "$HOME/.cargo/env"
  #         cargo build --release

  #     - name: Upload build artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: Match Maker Server
  #         path: Match Maker Server/target/release/match_maker_server-${{ matrix.rust-channel }}
