name: Rust Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust-channel: ["stable"]

    runs-on: self-hosted
    container: ubuntu:lunar-20231128

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal --default-toolchain stable

      - name: Release Build
        run: cargo build --release
        working-directory: Match Maker Server/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Match Maker Server
          path: Match Maker Server/target/release/match_maker_server-${{ matrix.rust-channel }}
