name: Rust Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust-channel: ["stable"]

    runs-on: self-hosted
    container: ubuntu:lunar-20231128

    steps:
      - uses: actions/checkout@v4

      - name: Install cURL
        run: apt update && apt install -y curl

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable

      - name: Release Build
        run: |
          cd "Match Maker Server"
          source "$HOME/.cargo/env"
          cargo build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Match Maker Server
          path: Match Maker Server/target/release/match_maker_server-${{ matrix.rust-channel }}
