name: Godot Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CSharpVersion: 8.0.x

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        godot-version: [4.2.1]

    runs-on: self-hosted
    container: ubuntu:lunar-20231128

    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-dotnet@v4
        name: Setup .NET SDK
        with:
          dotnet-version: ${{ env.CSharpVersion }}

      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          # Version must include major, minor, and patch, and be >= 4.0.0
          version: ${{ matrix.godot-version }}
          # Use .NET-enabled version of Godot (the default is also true).
          use-dotnet: true

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: Godot Project/

      - name: Generate .NET Bindings
        run: godot --headless --build-solutions --quit || exit 0
        working-directory: Godot Project/

      - name: Build Project
        run: dotnet build
        working-directory: Godot Project/
