name: Godot Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CSharpVersion: 8.0.x

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        godot-version: [4.2.1]

    runs-on: self-hosted
    container: ubuntu:lunar-20231128

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: APT update
        run: apt update

      - name: APT install cURL
        run: apt install -y curl

      - name: APT install unzip
        run: apt install -y unzip

      - name: APT install libicu-dev
        run: apt install -y libicu-dev

      - uses: actions/setup-dotnet@v4
        name: Setup .NET SDK
        with:
          dotnet-version: ${{ env.CSharpVersion }}

      - uses: chickensoft-games/setup-godot@v1
        name: Setup Godot
        with:
          # Version must include major, minor, and patch, and be >= 4.0.0
          version: ${{ matrix.godot-version }}
          # Use .NET-enabled version of Godot (the default is also true).
          use-dotnet: true

      - name: Build Project
        run: |
          cd "Godot Project"
          dotnet restore
          godot --headless --build-solutions --quit || exit 0
          dotnet build
